id: os_ssh_server_alive_interval_configure
title: "Configure SSH ServerAliveInterval option set to $ODV"
discussion: |
  SSH _MUST_ be configured with an Active Server Alive Maximum Count set to $ODV. 
  
  Setting the Active Server Alive Maximum Count to $ODV (second) will log users out after a 15-minute interval of inactivity.

  NOTE: /etc/ssh/ssh_config will be automatically modified to its original state following any update or major upgrade to the operating system.
check: |
  /usr/bin/awk '/^ServerAliveInterval/{print $2}' /etc/ssh/ssh_config
result:
  integer: 1
fix: |
  [source,bash]
  ----
  /usr/bin/grep -q '^ServerAliveInterval' /etc/ssh/ssh_config && /usr/bin/sed -i.bak  's/.*ServerAliveInterval.*/ServerAliveInterval $ODV/' /etc/ssh/ssh_config || /bin/echo 'ServerAliveInterval $ODV' >> /etc/ssh/ssh_config
  ----
references:
  cce:
    - CCE-84919-0
  cci: 
    - N/A
  800-53r5:
    - SC-10
    - AC-12
  800-53r4: 
    - SC-10
  srg: 
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - 3.13.9
macOS:
  - "10.15"
odv:
  hint: "Number of seconds."
  default: 900
tags:
  - 800-53r5_moderate
  - 800-53r5_high
  - 800-171
  - cnssi-1253
  - 800-53r4_moderate
  - 800-53r4_high
mobileconfig: false
mobileconfig_info: