id: system_settings_siri_prefpane_disable
title: Disable the System Preference Pane for Siri
discussion: |
  This is required for compliance with the DISA STIG for macOS.

  The domain *com.apple.systempreferences* has been deprecated by Apple in macOS 13. The recommended way to disable System Setting Panes is to use the *DisabledSystemSettings* key.

  link:https://developer.apple.com/documentation/devicemanagement/systempreferences[]
check: |
  /usr/bin/profiles show -output stdout-xml | /usr/bin/xmllint --xpath '//key[text()="DisabledPreferencePanes"]/following-sibling::*[1]' - | /usr/bin/grep -c com.apple.preference.speech
result:
  integer: 1
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - N/A
    controls v8:
      - N/A
macOS:
  - '14.0'
tags:
  - none
severity: medium
mobileconfig: true
mobileconfig_info:
  com.apple.systempreferences:
    DisabledPreferencePanes:
      - com.apple.preference.speech
