id: system_settings_location_services_menu_enforce
title: Ensure Location Services Is In the Menu Bar
discussion: |
  Location Services menu item _MUST_ be enabled.
check: |
  /usr/bin/osascript -l JavaScript << EOS
  $.NSUserDefaults.alloc.initWithSuiteName('com.apple.locationmenu')\
  .objectForKey('ShowSystemServices').js
  EOS
result:
  string: 'true'
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - N/A
  cci:
    - N/A
  800-53r5:
    - N/A
  800-53r4:
    - N/A
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 2.6.1.2 (level 2)
    controls v8:
      - 4.1
      - 4.8
macOS:
  - '14.0'
tags:
  - cis_lvl2
mobileconfig: true
mobileconfig_info:
  com.apple.locationmenu:
    ShowSystemServices: true
